name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build Angular
        run: npm run build -c=production --base-href=/mmah/

      - name: Push to Another Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Define the target repository
          TARGET_REPO="https://x-access-token:${GITHUB_TOKEN}@github.com/alkhwarizmilab/mmah.git"

          # Clone the target repository
          git clone $TARGET_REPO target-repo
          cd target-repo

          # Remove existing files
          rm -rf *

          # Copy new build artifacts
          cp -r ../dist/mmanimalhealthltd/browser/* .

          # Commit and push changes
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy updated build [skip ci]"
          git push
